import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
// --- We use our working 'apiRequest' helper ---
import { apiRequest } from "../api/apiClient";

// --- This is the correct, full API interface ---
interface Contact {
  idLead: number;
  idUser: number;
  company: string;
  email: string;
  phone: string;
  status: string;
  leadSource: string;
  priority: string;
  created_At: string;
  updated_At: string;
  last_Contact_Date: string;
  next_Follow_Up_Date: string;
}

function Contacts() {
  const navigate = useNavigate();

  // --- API-driven state ---
  const [contacts, setContacts] = useState<Contact[]>([]);
  
  // --- UI state from your teammate's version ---
  const [searchTerm, setSearchTerm] = useState("");
  const [showForm, setShowForm] = useState(false);

  // --- Form fields for new contact ---
  const [name, setName] = useState(''); // Note: Your API uses 'company', not 'name'
  const [company, setCompany] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [source, setSource] = useState('voice');

  // --- This is our working API fetch logic ---
  useEffect(() => {
    const fetchContacts = async () => {
      try {
        const data = await apiRequest<Contact[]>("leads");
        setContacts(data);
      } catch (err) {
        console.error("Error fetching contacts:", err);
      }
    };
    fetchContacts();
  }, []); // Runs once on page load

  // --- This is our working API delete logic ---
  const deleteContact = async (id: number) => {
    if (!confirm("Are you sure you want to delete this contact?")) return;
    try {
      await apiRequest(`leads/${id}`, "DELETE");
      setContacts((prev) => prev.filter((contact) => contact.idLead !== id));
    } catch (err) {
      console.error("Error deleting contact:", err);
    }
  };

  // --- This is the NEW API-driven 'Add Contact' logic ---
  const handleAddContact = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!company || !email) {
      alert("Company and Email are required.");
      return;
    }

    const newContact = {
      // idLead is auto-generated by the DB
      idUser: 1, // We'll hardcode '1' for now, this should come from the logged-in user
      company: company,
      email: email,
      phone: phone,
      leadSource: source,
      status: "New", // Default status
      priority: "Medium", // Default priority
    };

    try {
      // POST the new contact to the C# API
      await apiRequest("leads", "POST", newContact);

      // Reset form and hide it
      setCompany('');
      setEmail('');
      setPhone('');
      setSource('voice');
      setShowForm(false);
      
      // Refresh the contacts list from the API
      const data = await apiRequest<Contact[]>("leads");
      setContacts(data);

    } catch (err) {
      console.error("Error adding contact:", err);
      alert("Failed to add contact. Please try again.");
    }
  };
  
  // --- Filter logic (now uses correct API properties) ---
  const filteredContacts = contacts.filter(
    (contact) =>
      contact.company?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      contact.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      contact.phone?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const exportContacts = () => {
    alert("Exporting contacts to CSV...");
  };

  // --- This is your teammate's nicer UI ---
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 w-full">
        <div className="w-full px-4">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <div className="flex-shrink-0 flex items-center gap-3">
                <div className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z"
                    />
                  </svg>
                </div>
                <div>
                  <span className="text-xl font-bold text-slate-900">
                    VoiceCRM
                  </span>
                  <span className="text-xs text-blue-600 font-medium ml-2 bg-blue-50 px-2 py-1 rounded">
                    Zero-Click
                  </span>
                </div>
              </div>
              <nav className="hidden md:ml-8 md:flex space-x-1">
                <button
                  onClick={() => navigate("/dashboard")}
                  className="text-slate-600 hover:text-slate-900 px-4 py-2 rounded-lg text-sm font-medium"
                >
                  Dashboard
                </button>
                <button
                  onClick={() => navigate("/contacts")}
                  className="text-slate-700 bg-red-50 px-4 py-2 rounded-lg text-sm font-medium"
                >
                  Contacts
                </button>
                <button
                  onClick={() => navigate("/recordings")}
                  className="text-slate-600 hover:text-slate-900 px-4 py-2 rounded-lg text-sm font-medium"
                >
                  Recordings
                </button>
                <button
                  onClick={() => navigate("/settings")}
                  className="text-slate-600 hover:text-slate-900 px-4 py-2 rounded-lg text-sm font-medium"
                >
                  Settings
                </button>
              </nav>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => setShowForm((prev) => !prev)}
                className="bg-red-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-red-700"
              >
                {showForm ? "Cancel" : "Add Contact"}
              </button>
              <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-white font-medium text-sm">
                JD
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-slate-900 mb-2">Contacts</h1>
          <p className="text-slate-600">
            {contacts.length} contacts auto-created from voice conversations
          </p>
        </div>

        {/* Formulaire affiché seulement si showForm = true */}
        {showForm && (
          <div className="bg-white rounded-lg border border-slate-200 p-6 mb-6 shadow-sm">
            <form
              onSubmit={handleAddContact}
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4"
            >
              <input
                value={company}
                onChange={(e) => setCompany(e.target.value)}
                placeholder="Company"
                className="px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring-2 focus:ring-red-500"
              />
              <input
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Email"
                className="px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring-2 focus:ring-red-500"
              />
              <input
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                placeholder="Phone"
                className="px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring-2 focus:ring-red-500"
              />
              <select
                value={source}
                onChange={(e) => setSource(e.target.value)}
                className="px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring-2 focus:ring-red-500"
              >
                <option value="voice">Voice</option>
                <option value="call">Call</option>
                <option value="email">Email</option>
              </select>
              <div className="sm:col-span-2 md:col-span-4 flex justify-end">
                <button
                  type="submit"
                  className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                >
                  Save Contact
                </button>
              </div>
            </form>
          </div>
        )}

        {/* Search & Actions */}
        <div className="bg-white rounded-lg border border-slate-200 p-6 mb-6">
          <div className="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center">
            <div className="flex-1 w-full sm:max-w-md">
              <input
                type="text"
                placeholder="Search contacts..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
              />
            </div>
            <div className="flex gap-3">
              <button
                onClick={exportContacts}
                className="px-4 py-2 border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 text-sm font-medium"
              >
                Export
              </button>
              <button
                onClick={() => setShowForm((prev) => !prev)}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 text-sm font-medium"
              >
                {showForm ? "Cancel" : "Add Contact"}
              </button>
            </div>
          </div>
        </div>

        {/* Contacts Table (Teammate's UI, API data) */}
        <div className="bg-white rounded-lg border border-slate-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                    Company
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                    Contact Info
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                    Source
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {filteredContacts.map((contact) => (
                  <tr key={contact.idLead} className="hover:bg-slate-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 font-medium text-sm mr-3">
                          {contact.company ? contact.company.substring(0, 2) : 'N/A'}
                        </div>
                        <div className="text-sm font-medium text-slate-900">
                          {contact.company}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-slate-900">
                        {contact.email}
                      </div>
                      <div className="text-sm text-slate-500">
                        {contact.phone}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900">
                      {contact.status}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span
                        className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                          contact.leadSource === "voice"
                            ? "bg-green-100 text-green-800"
                            : contact.leadSource === "call"
                            ? "bg-blue-100 text-blue-800"
                            : "bg-purple-100 text-purple-800"
                        }`}
                      >
                        {contact.leadSource}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <button
                        onClick={() =>
                          alert(`Viewing details for ${contact.company}`)
                        }
                        className="text-blue-600 hover:text-blue-900 mr-4"
                      >
                        View
                      </button>
                      <button
                        onClick={() => deleteContact(contact.idLead)}
                        className="text-red-600 hover:text-red-900"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {contacts.length > 0 && filteredContacts.length === 0 && (
          <div className="text-center py-12">
            <div className="text-slate-400 text-lg">No contacts found</div>
            <div className="text-slate-500 text-sm mt-2">
              Try adjusting your search terms
            </div>
          </div>
        )}
        {contacts.length === 0 && (
          <div className="text-center py-12">
            <div className="text-slate-400 text-lg">Loading contacts...</div>
          </div>
        )}
      </main>
    </div>
  );
}

export default Contacts;